name: gtr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.4
  easy_localization: ^3.0.8
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  smooth_page_indicator: ^2.0.1
  pin_code_fields: ^8.0.1
  iconsax: ^0.0.8
  flutter_staggered_grid_view: ^0.7.0
  circular_reveal_animation: ^2.0.2
  dio: ^5.9.0
  riverpod: ^3.2.0
  flutter_riverpod: ^3.2.0
  cached_network_image: ^3.4.1
  video_player: ^2.10.1
  onesignal_flutter: ^5.4.0
  pinput: ^6.0.1
  material: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: PingAR LT
      fonts:
        - asset: assets/fonts/PingAR+LT-Hairline.otf
          weight: 100
        - asset: assets/fonts/PingAR+LT-Thin.otf
          weight: 200
        - asset: assets/fonts/PingAR+LT-ExtraLight.otf
          weight: 300
        - asset: assets/fonts/PingAR+LT-Light.otf
          weight: 400
        - asset: assets/fonts/PingAR+LT-Regular.otf
          weight: 500
        - asset: assets/fonts/PingAR+LT-Medium.otf
          weight: 600
        - asset: assets/fonts/PingAR+LT-Bold.otf
          weight: 700
        - asset: assets/fonts/PingAR+LT-Heavy.otf
          weight: 800
        - asset: assets/fonts/PingAR+LT-Black.otf
          weight: 900

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/